apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-customgpt
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  awsElasticBlockStore:
    volumeID: <your-volume-id>
    fsType: ext4
